### ISSUE TITLE
Coherence-Signed failed

### ISSUE THREAD

**Issue by ryanbrandenburg** [ryanbrandenburg/Coherence-Signed#2]
Coherence-Signed failed with the following errors:
[10:40:50]E:	 [Step 2/4] Process exited with code 1
[10:40:50]E:	 [Step 2/4] Step Build and Sign packages (Command Line) failed
[10:40:51]E:	 [Step 2/4] Error message is logged
http://aspnetci/viewLog.html?buildId=510893&buildTypeId=CoherenceSigned
CC $@Eilon, @mkArtakMSFT, @muratg

**Comment by Eilon** [comment]
Is this the root error?

```
[10:40:47][Step 2/4]     [drop.exe][VERBOSE] 2018-07-20T10:40:47.5164575-07:00  UploadAndAssociateFilesAsync transferring 4 files
[10:40:47][Step 2/4]     [drop.exe][VERBOSE] 2018-07-20T10:40:47.5234460-07:00  ArtifactHttpClientFactory.CreateVssHttpClient: BlobStore2HttpClient with BaseUri: https://devdiv.vsblob.visualstudio.com/, MaxRetries:5, SendTimeout:00:10:00
[10:40:48][Step 2/4]     [drop.exe][VERBOSE] 2018-07-20T10:40:48.0462116-07:00  ArtifactHttpRetryMessageHandler.TraceHttpRequestFailed: https://devdiv.vsblob.visualstudio.com/_apis/, HttpStatusCode.Unauthorized, activity ee3a1c3f-76e0-4518-ab33-8d0e3058857c
[10:40:48][Step 2/4]     [drop.exe][VERBOSE] 2018-07-20T10:40:48.0462116-07:00  ArtifactHttpRetryMessageHandler.SendAsync: https://devdiv.vsblob.visualstudio.com/_apis/ attempt 1/6 failed with StatusCode Unauthorized, IsRetryableResponse False
[10:40:48][Step 2/4]     [drop.exe][VERBOSE] 2018-07-20T10:40:48.2001540-07:00  Failed to publish a file group 1: Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: The requested operation is not allowed.
[10:40:48][Step 2/4]        at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__53.MoveNext()
[10:40:48][Step 2/4]     --- End of stack trace from previous location where exception was thrown ---
[10:40:48][Step 2/4]        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[10:40:48][Step 2/4]        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[10:40:48][Step 2/4]        at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__51.MoveNext()
[10:40:48][Step 2/4]     --- End of stack trace from previous location where exception was thrown ---
[10:40:48][Step 2/4]        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[10:40:48][Step 2/4]        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[10:40:48][Step 2/4]        at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__47`1.MoveNext()
[10:40:48][Step 2/4]     --- End of stack trace from previous location where exception was thrown ---
[10:40:48][Step 2/4]        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[10:40:48][Step 2/4]        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[10:40:48][Step 2/4]        at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<GetResourceLocationsAsync>d__65.MoveNext()
[10:40:48][Step 2/4]     --- End of stack trace from previous location where exception was thrown ---
[10:40:48][Step 2/4]        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[10:40:48][Step 2/4]        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[10:40:48][Step 2/4]        at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<EnsureResourceLocationsPopulated>d__66.MoveNext()
[10:40:48][Step 2/4]     --- End of stack trace from previous location where exception was thrown ---
[10:40:48][Step 2/4]        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[10:40:48][Step 2/4]        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[10:40:48][Step 2/4]        at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<GetResourceLocationAsync>d__64.MoveNext()
[10:40:48][Step 2/4]     --- End of stack trace from previous location where exception was thrown ---
[10:40:48][Step 2/4]        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[10:40:48][Step 2/4]        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[10:40:48][Step 2/4]        at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<CreateRequestMessageAsync>d__34.MoveNext()
[10:40:48][Step 2/4]     --- End of stack trace from previous location where exception was thrown ---
[10:40:48][Step 2/4]        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[10:40:48][Step 2/4]        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[10:40:48][Step 2/4]        at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__31.MoveNext()
[10:40:48][Step 2/4]     --- End of stack trace from previous location where exception was thrown ---
[10:40:48][Step 2/4]        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[10:40:48][Step 2/4]        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[10:40:48][Step 2/4]        at Microsoft.VisualStudio.Services.ItemStore.Common.ItemUploader.<>c__DisplayClass15_0.<GetBlobClient>b__1()
[10:40:48][Step 2/4]        at System.Lazy`1.CreateValue()
[10:40:48][Step 2/4]        at System.Lazy`1.LazyInitValue()
[10:40:48][Step 2/4]        at Microsoft.VisualStudio.Services.ItemStore.Common.ItemUploader.GetBlobClient(Uri contentServiceUri, CancellationToken cancellationToken)
[10:40:48][Step 2/4]        at Microsoft.VisualStudio.Services.ItemStore.Common.ItemUploader.<UploadMissing>d__23.MoveNext()
[10:40:48][Step 2/4]     --- End of stack trace from previous location where exception was thrown ---
[10:40:48][Step 2/4]        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[10:40:48][Step 2/4]        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[10:40:48][Step 2/4]        at Microsoft.VisualStudio.Services.ItemStore.Common.ItemUploader.<>c__DisplayClass20_3.<<UploadAndAssociateFilesHelperAsync>b__5>d.MoveNext()
[10:40:48][Step 2/4]     --- End of stack trace from previous location where exception was thrown ---
[10:40:48][Step 2/4]        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[10:40:48][Step 2/4]        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[10:40:48][Step 2/4]        at Microsoft.VisualStudio.Services.ItemStore.Common.TimedExecutionHelper.<TimedExecuteAsync>d__0.MoveNext()
[10:40:48][Step 2/4]     --- End of stack trace from previous location where exception was thrown ---
[10:40:48][Step 2/4]        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[10:40:48][Step 2/4]        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[10:40:48][Step 2/4]        at Microsoft.VisualStudio.Services.ItemStore.Common.ItemUploader.<UploadAndAssociateFilesHelperAsync>d__20.MoveNext()
[10:40:48][Step 2/4]     --- End of stack trace from previous location where exception was thrown ---
[10:40:48][Step 2/4]        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[10:40:48][Step 2/4]        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[10:40:48][Step 2/4]        at Microsoft.VisualStudio.Services.ItemStore.Common.ItemUploader.<UploadFilesAsync>d__10.MoveNext()
[10:40:48][Step 2/4]     --- End of stack trace from previous location where exception was thrown ---
[10:40:48][Step 2/4]        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[10:40:48][Step 2/4]        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[10:40:48][Step 2/4]        at Microsoft.VisualStudio.Services.Drop.App.Core.Telemetry.DropClientTelemetry.<MeasureUploadAsync>d__12.MoveNext()
[10:40:48][Step 2/4]     --- End of stack trace from previous location where exception was thrown ---
[10:40:48][Step 2/4]        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[10:40:48][Step 2/4]        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[10:40:48][Step 2/4]        at Microsoft.VisualStudio.Services.Drop.App.Core.DropServiceClient.<>c__DisplayClass98_0.<<PublishFilesWithPrecomputedHashAsync>b__1>d.MoveNext()
[10:40:48][Step 2/4]     --- End of stack trace from previous location where exception was thrown ---
[10:40:48][Step 2/4]        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[10:40:48][Step 2/4]        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[10:40:48][Step 2/4]        at Microsoft.VisualStudio.Services.Drop.App.Core.DropServiceClient.<>c__DisplayClass67_1`1.<<ProcessFileBlobDescriptorsPagedByBlobId>b__2>d.MoveNext().
```

If so, what is `ArtifactHttpClientFactory`, and what could this error be? Actual bad credentials? Or temporary VSTS failure?

**Comment by ryanbrandenburg** [comment]
This has since passed. It didn't look like it was flakiness, I think there was a problem with creds that we fixed.
